version: '3'
networks:
    working:
        driver: bridge
volumes:
    files-bot:
        driver: local
services:
    api:
        build: nexpbot
        container_name: nexpbotapi
        privileged: true
        working_dir: /var/www/html/NEBot
        command: php -S 0.0.0.0:8000 -t public public/index.php
        ports: 
            - 8000:8000
        depends_on: 
            - mongo
        networks: 
            - working
        volumes:
            - files-bot:/var/www/html/NEBot
    tibiaapi:
        build: tibiaapi
        container_name: tibiaapi
        ports: 
            - 3004:3004
        restart: always
        depends_on: 
            - web
        networks: 
            - working
    mongo:
        image: mongo
        restart: always
        container_name: dbmongo
        restart: always
        ports:
            - 27017:27017
            - 28017:28017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: M4n4g3R#B0t404
            MONGO_INITDB_DATABASE: lists
        networks: 
            - working
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        depends_on: 
            - mongo
        networks: 
            - working
    rabbitapi:
        build: rabbitapi
        container_name: rabbitapi
        restart: always
        ports: 
            - 3004:3004
        depends_on: 
            - mongo
            - rabbitmq
            - api
        networks:  
            - working
        
        
            